name = "mcmeta"
grammar = "json"
path_suffixes = ["mcmeta"]
autoclose_before = "}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
]
